### ISSUE TITLE
Feature request for new subscribers.

### ISSUE THREAD

**Issue by richardhearse** [DOWRIGHTTV/hakcbot_asyncio#1]
Hi was checking to see if it would be a good idea to have a command that congratulates someone on subscribing. 

Example:

congrats(richardhearse)

"Yo richardhearse welcome to the team! Grab a beer and make yourself comfortable."

Example for re-sub:

resub(richardhearse)

"richardhearse, you are awesome! Thanks for being part of the family."

---------------------

There are just some simple ideas to recognize people for contributing.

**Comment by DOWRIGHTTV** [comment]
this sounds good. feel free to do a PR if you want to get linked as a contributor otherwise i can do it. make sure you use the correct command decorator arguments if so.

**Comment by richardhearse** [comment]
This is completed.
